### ISSUE TITLE
Bug: Progress messages aren't being captured by the adaptor

### ISSUE THREAD

**Issue by justinsaws** [aws-deadline/deadline-cloud-for-houdini#115]
### Expected Behaviour

The adaptor captures and reports Job progress back up toe Deadline Cloud.

### Current Behaviour

Houdini progress messages are not being captured so no progress information is communicated back to Deadline Cloud

### Reproduction Steps

Submit any Houdini Job

### Code Snippet

![image (5)](https://github.com/aws-deadline/deadline-cloud-for-houdini/assets/132946620/12c0d761-49a4-47d9-920e-3b5b21539013)

**Comment by epmog** [comment]
I believe this should actually be moved to the openjd-adaptor-runtime-for-python repo since I believe the openjd messages are actually being prefixed with `STDOUT`, so they're not being captured by the worker agent.

**Comment by epmog** [comment]
I believe this should actually be moved to the [openjd-adaptor-runtime-for-python](https://github.com/OpenJobDescription/openjd-adaptor-runtime-for-python) repo since I believe the openjd messages from daemons are being sent to devnull. I believe the standard run command would work. Filing ticket there instead.

**Comment by epmog** [comment]
This will be addressed by https://github.com/OpenJobDescription/openjd-adaptor-runtime-for-python/issues/109
