### ISSUE TITLE
Bug: Clicking "Parse Files" in Houdini clears manually added assets from the asset list

### ISSUE THREAD

**Issue by justinsaws** [aws-deadline/deadline-cloud-for-houdini#116]
### Expected Behaviour

The Houdini submitter shouldn't clear out manually added files from the asset lists.

### Current Behaviour

If you click "Parse Files", any manually added files are deleted from the asset list.

### Reproduction Steps

1. Manually add files to the asset list
2. Click "Parse Files"
3. Previous entries are removed.

### Code Snippet

https://github.com/aws-deadline/deadline-cloud-for-houdini/blob/mainline/src/deadline/houdini_submitter/python/deadline_cloud_for_houdini/submitter.py#L483-L492

**Comment by epmog** [comment]
Other integrations that leverage the deadline-cloud UI track the automatically detected files compared to the manually entered files. As part of some of the other parse files fixes, once we're confident we're not adding problematic inputs, we can do the same here.

The code snippet here actually throws away everything when running the parsing, so we'll have to ensure we can identify the manually added ones vs. automatic since they're currently all just parms on the deadline-cloud rop node.

Can we add hidden metadata/invisible property of the parm that lets us know which ones are which?
